# Generated by Django 3.1 on 2020-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('short_description', models.CharField(max_length=100, verbose_name='Short description')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('quantity_of_lectures', models.IntegerField(verbose_name='Quantity of lectures')),
            ],
        ),
    ]
